# Generated by Django 5.0 on 2024-04-15 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayQuiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondetail',
            name='quizCard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='PlayQuiz.quizcard'),
        ),
    ]
