# Generated by Django 5.0 on 2024-04-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('moderator', 'moderator')], max_length=10),
        ),
    ]
